#!/usr/bin/python3
import sys
import re
from utils import *
from natural_language import natural_language
from simply_form import irreductible
from simply_form import get_fraction
from simply_form import get_complex

def found_x(before, after):
    maxi = 0
    tab = []
    reg = "(((-|\+)? {0,}\d+(\.\d+)?) ?\*? {0,}x\^(\d+))"
    bX = re.findall(reg, before)
    aX = re.findall(reg, after)
    for match_b in bX :
        a, b = 0, 0
        before = before.replace(match_b[0], '')
        b += float(re.sub(r"\s+", "", match_b[1], flags=re.UNICODE))
        for match_a in aX :
            if int(match_b[4]) == int(match_a[4]):
                a += float(re.sub(r"\s+", "", match_a[1], flags=re.UNICODE))
                after = after.replace(match_a[0], '')
                aX.remove(match_a)
        try :
            old = tab[int(match_b[4])]
            tab[int(match_b[4])] = (old + b) - a
        except :
            i = int(match_b[4])
            tab = append_tab(tab, i)
            tab[i] = b-a
        if int(match_b[4]) > maxi:
            maxi = int(match_b[4])
    if aX != []:
        for match in aX :
            a = 0
            a += float(re.sub(r"\s+", "", match[1], flags=re.UNICODE))
            after = after.replace(match[0], '')
            try :
                old = tab[int(match[4])]
                tab[int(match[4])] = old - a
            except :
                i = int(match[4])
                tab = append_tab(tab, i)
                tab[i] = (-a)
            if int(match[4]) > maxi:
                maxi = int(match[4])
    return(tab, maxi, before.strip(), after.strip())

def create_reduce_form(tab):
    str_red = ''
    str_nat = ''
    first = True
    X = 0
    for i in tab :
        if i != 0:
            signX = sign(i)
            if first == True and signX == '+':
                signX = ''
            first = False
            str_red += '{} {} * X^{} '.format(signX, abs(i), X)
            if X == 0 :
                str_nat += '{} {} '.format(signX, abs(i))
            elif X == 1:
                str_nat += '{} {}X '.format(signX, abs(i))
            else :
                str_nat += '{} {}X^{} '.format(signX, abs(i), X)
        X += 1
    if str_red != '' :
        str_red += '= 0'
    else :
        str_red += "0 * X^0 = 0 * X^0"
    if str_nat != '' :
        str_nat += '= 0'
    else :
        str_nat += "0 = 0"
    return(str_red.strip(), str_nat.strip())

def reduce_form(before, after):
    tab, maxi, before, after = found_x(before, after)
    if before == '' and after == '' or before == '0' and after == '' or before == '' and after == '0' or before == '0' and after == '0':
        red, nat = create_reduce_form(tab)
        print("Reduced form :", red)
        print("Natural form :", nat)
        if len(tab) < 3 :
            tab = append_tab(tab, 3)
        return(tab[0], tab[1], tab[2], maxi)
    else :
        tab, before, after, maxi = natural_language(tab, before.strip(), after.strip(), maxi)
        if before == '' and after == '' or before == '0' and after == '' or before == '' and after == '0' or before == '0' and after == '0':
            red, nat = create_reduce_form(tab)
            print("Reduced form :", red)
            print("Natural form :", nat)
            if len(tab) < 3 :
                tab = append_tab(tab, 3)
            return(tab[0], tab[1], tab[2], maxi)
        else :
            print("Wrong format")
            return(None, None, None, None)

def aff_deg_minus(a, b, c, maxi):
    if maxi == 0:
        if c == 0:
            print("Any real is solution")
        else :
            print("Impossible solution")
    elif (maxi == 1):
        a, b = b, c
        if a == 0 and b != 0:
            print("No solution")
        elif a == 0 and b == 0:
            print("Any real is solution")
        else :
            print("The solution is :")
            res = -(b / a)
            if res == 0:
                res = 0
            else :
                fract = irreductible(-b, a)
                if fract != None :
                    print(fract, end=" => ")
            print(res)

def aff_delta_negative(a, b, c, delta):
    print("Discriminant is strictly negative, the two solutions are : ")
    abs_b = abs(b)
    str_sign = ('{} {}'.format(sign_without_plus(-b), abs_b)).strip()
    str_plus, str_min = get_complex(delta, b, a)
    print("({} + i√({})) / (2 * {})".format(str_sign, abs(delta), a+0), end = ' => ')
    if (str_plus):
        print(str_plus, end = ' => ')
    print("{}i + {}".format((sqrt(-delta) / (2 * a))+0, (b / (2 * a))+0))
    print("({} - i√({})) / (2 * {})".format(abs_b, abs(delta), a+0), end = ' => ')
    if (str_min):
        print(str_min, end = ' => ')
    print("{}i + {}".format((-sqrt(-delta) / (2 * a))+0, (b / (2 * a))+0))

def aff_delta_positive(a, b, c, delta):
    print("Discriminant is strictly positive, the two solutions are :")
    abs_b = abs(b)
    str_sign = ('{} {}'.format(sign_without_plus(-b), abs_b)).strip()
    print("({} - √({})) / (2 * {})".format(str_sign, delta+0, a+0), end = ' => ')
    str_fract = get_fraction(b, a, delta, '-')
    if str_fract != None :
        print(str_fract, end = ' => ')
    print(((-b - sqrt(delta)) / (2 * a))+0)
    print("({} + √({})) / (2 * {})".format(str_sign, delta+0, a+0), end = ' => ')
    str_fract = get_fraction(b, a, delta, '+')
    if str_fract != None :
        print(str_fract, end = ' => ')
    print(((-b + sqrt(delta)) / (2 * a))+0)

def aff_deg_second(a, b, c, maxi):
    delta = b*b - 4*a*c
    if delta > 0:
        aff_delta_positive(a, b, c, delta)
    elif delta == 0 :
        print("Discriminant is 0. The solution is :")
        print(((-b) / (2 * a))+0)
    elif delta < 0 :
        aff_delta_negative(a, b, c, delta)

def main():
    if (len(sys.argv)) != 2:
        print('''Bad argument.\nUsage : ./computor.py "[polynomial equation]"''')
    else :
        before, after = None, None
        expr = sys.argv[1]
        m = re.search("(.*) ?= ?(.*)", expr)
        if m :
            if m.group(1):
                before = m.group(1).lower().strip()
            if m.group(2):
                after = m.group(2).lower().strip()
            if before is None or after is None :
                print("Equation not found")
            else :
                c, b, a, maxi = reduce_form(before, after)
                if c is not None:
                    print('Polynomial degree:', maxi, end="\n\n")
                    if (maxi == 0 or maxi == 1) :
                        aff_deg_minus(a, b, c, maxi)
                    elif (maxi == 2):
                        aff_deg_second(a, b, c, maxi)
                    else :
                        print("The polynomial degree is stricly greater than 2, I can't solve.")
        else :
            print("Wrong format")

if __name__ == '__main__':
    main()
